name: Deploy to websupport

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: 🔨 Setup Yarn
      uses: borales/actions-yarn@v3.0.0
      with:
        cmd: install # will run `yarn install` command

    - name: 🔨 Build Project
      uses: borales/actions-yarn@v3.0.0
      with:
        cmd: build # will run `yarn build` command

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.1
      with:
        server: hrabcak.eu
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        local-dir: build/
        server-dir: hrabcak.eu/web/ivan/${{ github.event.repository.name }}
